package hu.deposoft.webshop.integrations.wordpress;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Verifies the WordPress phpass (portable, $P$) hash format. Vectors generated by
 * the live WP container's class-phpass.php (PasswordHash(8, true), 8192 iters) —
 * the same code that produced the dump's stored hashes.
 */
class WordPressPasswordEncoderTest {

    private final WordPressPasswordEncoder encoder = new WordPressPasswordEncoder();

    @Test
    void matchesPhpassVectorsFromWordPress() {
        assertThat(encoder.matches("Secret123", "$P$BDxkiVZNDAZCUYJPWfhZ/YRxoK5khY1")).isTrue();
        assertThat(encoder.matches("helloVilág", "$P$BO.sKsMpfAKPRvT8UXopQyOTTSVixM1")).isTrue();
        assertThat(encoder.matches("aaaa", "$P$BhGQxZm9ZpPxS6wC1AnuE6Jgq3RRY10")).isTrue();
    }

    @Test
    void rejectsWrongPassword() {
        assertThat(encoder.matches("wrong", "$P$BDxkiVZNDAZCUYJPWfhZ/YRxoK5khY1")).isFalse();
        assertThat(encoder.matches("Secret124", "$P$BDxkiVZNDAZCUYJPWfhZ/YRxoK5khY1")).isFalse();
    }

    @Test
    void handlesMalformedHashGracefully() {
        assertThat(encoder.matches("x", "not-a-phpass-hash")).isFalse();
        assertThat(encoder.matches("x", "")).isFalse();
        assertThat(encoder.matches("x", "$P$B")).isFalse();
    }

    @Test
    void encodeIsUnsupported() {
        assertThatThrownBy(() -> encoder.encode("x"))
                .isInstanceOf(UnsupportedOperationException.class);
    }
}
