-- Workshops (T24 phase 2): a workshop is a product (type=WORKSHOP); each session
-- is a variant with a linked capacity + start time. Availability = capacity −
-- non-cancelled bookings − live holds (computed in AvailabilityService).

ALTER TABLE product DROP CONSTRAINT IF EXISTS product_type_check;
ALTER TABLE product ADD CONSTRAINT product_type_check CHECK (type IN ('SIMPLE', 'VARIABLE', 'WORKSHOP'));

CREATE TABLE workshop_session (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL UNIQUE REFERENCES variant (id),
    start_at   TIMESTAMPTZ NOT NULL,
    capacity   INT NOT NULL CHECK (capacity >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
