-- Per-source invoicing outcome (T24 phase 3). One row per (order, source):
-- BILLINGO = an invoice our app issued (number + public URL); KULCS_SOFT = the
-- order was handed to Kulcs-Soft (they issue). FAILED rows are retried.

CREATE TABLE invoice (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL REFERENCES orders (id),
    source         TEXT NOT NULL CHECK (source IN ('KULCS_SOFT', 'BILLINGO')),
    state          TEXT NOT NULL CHECK (state IN ('ISSUED', 'PUSHED', 'FAILED')),
    invoice_number TEXT,
    public_url     TEXT,
    external_id    TEXT,
    message        TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (order_id, source)
);

CREATE INDEX ix_invoice_state ON invoice (state);
