-- Blog CMS (T-BLOG): DB-backed posts, managed categories, recommended products by SKU.
CREATE TABLE blog_category (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT NOT NULL,
    slug  TEXT NOT NULL UNIQUE
);

CREATE TABLE blog_post (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            TEXT NOT NULL UNIQUE,
    title           TEXT NOT NULL,
    excerpt         TEXT,
    body_markdown   TEXT NOT NULL DEFAULT '',
    cover_image_key TEXT,
    status          TEXT NOT NULL DEFAULT 'DRAFT',
    published_at    TIMESTAMPTZ,
    seo_title       TEXT,
    seo_description TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_blog_post_status_published_at ON blog_post (status, published_at DESC);

CREATE TABLE blog_post_category (
    blog_post_id     BIGINT NOT NULL REFERENCES blog_post (id) ON DELETE CASCADE,
    blog_category_id BIGINT NOT NULL REFERENCES blog_category (id) ON DELETE CASCADE,
    PRIMARY KEY (blog_post_id, blog_category_id)
);

CREATE TABLE blog_post_product (
    blog_post_id BIGINT NOT NULL REFERENCES blog_post (id) ON DELETE CASCADE,
    sku          TEXT NOT NULL,
    sort_order   INT NOT NULL DEFAULT 0,
    PRIMARY KEY (blog_post_id, sku)
);
