-- Blog sidebar (T-BLOG-SIDEBAR): admin-ready, generic block model.
ALTER TABLE blog_category
    ADD COLUMN sidebar_hidden BOOLEAN NOT NULL DEFAULT false;
-- keep the catch-all out of the public sidebar
UPDATE blog_category SET sidebar_hidden = true WHERE slug = 'uncategorized';

CREATE TABLE sidebar_block (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_type    TEXT    NOT NULL,
    display_order INT     NOT NULL,
    enabled       BOOLEAN NOT NULL DEFAULT true,
    content       TEXT    NOT NULL
);
CREATE INDEX ix_sidebar_block_order ON sidebar_block (display_order);

INSERT INTO sidebar_block (block_type, display_order, enabled, content) VALUES
 ('AUTHOR', 1, true,
  '{"name":"Szendrődi Enikő","bio":"Szendrődi Enikő vagyok, a Nemiskacat tulajdonosa, hobbibútorfestő.","photoUrl":"/design/assets/blog/author-placeholder.svg"}'),
 ('CATEGORIES', 2, true,
  '{"title":"Kategóriák"}'),
 ('CTA', 3, true,
  '{"title":"Már tudod is mit fogsz festeni?","buttonLabel":"Irány a webshop","url":"/termekkategoria/kretafestek-annie-sloan-chalk-paint/","imageUrl":"/design/assets/blog/cta-placeholder.svg"}'),
 ('CONTACT', 4, true,
  '{"title":"Elérhetőség","phone":"+36 20 269 9113","email":"nemiskacat@nemiskacat.hu","address":"Biatorbágy, Csillag u. 7."}'),
 ('SOCIAL', 5, true,
  '{"title":"Kövess minket","links":[{"network":"facebook","url":"https://www.facebook.com/Nemiskacat"},{"network":"instagram","url":"https://www.instagram.com/nemiskacat/"},{"network":"youtube","url":"https://www.youtube.com/user/Nemiskacatponthu"}]}');
