-- Blog tags (migrated from WordPress post_tag). Parallel to blog_category (V22).
CREATE TABLE blog_tag (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE
);
CREATE TABLE blog_post_tag (
    blog_post_id BIGINT NOT NULL REFERENCES blog_post (id) ON DELETE CASCADE,
    blog_tag_id  BIGINT NOT NULL REFERENCES blog_tag (id)  ON DELETE CASCADE,
    PRIMARY KEY (blog_post_id, blog_tag_id)
);
