-- Product tags (migrated from WooCommerce product_tag). Parallel to category/product_category (V2).
CREATE TABLE product_tag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id BIGINT NOT NULL UNIQUE,   -- Woo term id
    slug        TEXT NOT NULL,
    name        TEXT NOT NULL
);
CREATE TABLE product_tag_map (
    product_id     BIGINT NOT NULL REFERENCES product (id)     ON DELETE CASCADE,
    product_tag_id BIGINT NOT NULL REFERENCES product_tag (id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, product_tag_id)
);
