-- Catalog data model (T3): categories, products, variants, attributes, images.
-- Uniform variant model: every product has >=1 variant (simple = one default
-- variant); stock and price live on the variant. Money in minor units (HUF=forint).
-- Slugs and woo_id/sku are preserved from WooCommerce for SEO and idempotent import.

CREATE TABLE category (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    woo_term_id      BIGINT UNIQUE,
    slug             TEXT NOT NULL UNIQUE,
    name             TEXT NOT NULL,
    parent_id        BIGINT REFERENCES category (id),
    sort_order       INT NOT NULL DEFAULT 0,
    description      TEXT,
    seo_title        TEXT,
    meta_description TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE product (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    woo_id            BIGINT UNIQUE,
    slug              TEXT NOT NULL UNIQUE,
    name              TEXT NOT NULL,
    type              TEXT NOT NULL CHECK (type IN ('SIMPLE', 'VARIABLE')),
    status            TEXT NOT NULL CHECK (status IN ('PUBLISHED', 'DRAFT')),
    lifecycle         TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (lifecycle IN ('ACTIVE', 'DISCONTINUED')),
    short_description TEXT,
    description       TEXT,
    tax_class         TEXT,
    seo_title         TEXT,
    meta_description  TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE product_category (
    product_id  BIGINT NOT NULL REFERENCES product (id),
    category_id BIGINT NOT NULL REFERENCES category (id),
    PRIMARY KEY (product_id, category_id)
);

CREATE TABLE attribute (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    woo_attribute_id BIGINT UNIQUE,
    slug             TEXT NOT NULL UNIQUE,
    label            TEXT NOT NULL,
    type             TEXT NOT NULL
);

CREATE TABLE attribute_value (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_id BIGINT NOT NULL REFERENCES attribute (id),
    slug         TEXT NOT NULL,
    label        TEXT NOT NULL,
    sort_order   INT NOT NULL DEFAULT 0,
    UNIQUE (attribute_id, slug)
);

CREATE TABLE product_attribute (
    product_id    BIGINT NOT NULL REFERENCES product (id),
    attribute_id  BIGINT NOT NULL REFERENCES attribute (id),
    position      INT NOT NULL DEFAULT 0,
    for_variation BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (product_id, attribute_id)
);

CREATE TABLE variant (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT NOT NULL REFERENCES product (id),
    woo_id              BIGINT,
    sku                 TEXT,
    is_default          BOOLEAN NOT NULL DEFAULT FALSE,
    regular_price_huf   BIGINT,
    sale_price_huf      BIGINT,
    sale_from           TIMESTAMPTZ,
    sale_to             TIMESTAMPTZ,
    weight_grams        INT,
    position            INT NOT NULL DEFAULT 0,
    manage_stock        BOOLEAN NOT NULL DEFAULT TRUE,
    last_sync_qty       INT,
    last_sync_at        TIMESTAMPTZ,
    manual_availability TEXT CHECK (manual_availability IN ('TEMPORARILY_UNAVAILABLE', 'PREORDER')),
    low_stock_threshold INT NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- woo_id / sku are unique only when present (a synthetic default variant has neither).
CREATE UNIQUE INDEX ux_variant_woo_id ON variant (woo_id) WHERE woo_id IS NOT NULL;
CREATE UNIQUE INDEX ux_variant_sku ON variant (sku) WHERE sku IS NOT NULL;
CREATE INDEX ix_variant_product ON variant (product_id);

CREATE TABLE variant_attribute_value (
    variant_id         BIGINT NOT NULL REFERENCES variant (id),
    attribute_value_id BIGINT NOT NULL REFERENCES attribute_value (id),
    PRIMARY KEY (variant_id, attribute_value_id)
);

CREATE TABLE product_image (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL REFERENCES product (id),
    variant_id  BIGINT REFERENCES variant (id),
    storage_key TEXT NOT NULL,
    alt         TEXT,
    position    INT NOT NULL DEFAULT 0,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_product_image_product ON product_image (product_id);
