-- Site-wide social links (single source of truth for header + blog sidebar).
CREATE TABLE social_link (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network       TEXT NOT NULL,
    url           TEXT NOT NULL,
    display_order INT  NOT NULL
);
INSERT INTO social_link (network, url, display_order) VALUES
 ('facebook',  'https://www.facebook.com/Nemiskacat',        1),
 ('instagram', 'https://www.instagram.com/nemiskacat/',      2),
 ('youtube',   'https://www.youtube.com/user/Nemiskacatponthu', 3);
