-- Content pages (WordPress page migration): DB-backed static pages rendered at root /{slug}.
CREATE TABLE content_page (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id     BIGINT UNIQUE,
    slug            TEXT NOT NULL UNIQUE,
    title           TEXT NOT NULL,
    body_html       TEXT NOT NULL DEFAULT '',
    status          TEXT NOT NULL DEFAULT 'DRAFT',
    seo_title       TEXT,
    seo_description TEXT,
    published_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_content_page_status ON content_page (status);
