-- Server-side guest cart (T8). The browser holds only the random token in an
-- HttpOnly cookie; user_id is filled on login-merge (T13). Prices are not stored
-- on items — always computed at read; checkout locks prices (T9).

CREATE TABLE cart (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      TEXT NOT NULL UNIQUE,
    user_id    BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE cart_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT NOT NULL REFERENCES cart (id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES variant (id),
    quantity   INT NOT NULL CHECK (quantity > 0),
    added_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (cart_id, variant_id)
);

CREATE INDEX ix_cart_item_cart ON cart_item (cart_id);
