-- Orders + checkout reservations (T9). Orders lock prices at placement (the cart
-- never stores prices). client_key enforces idempotent recording at the DB level.
-- Reservations are short checkout holds for flagged products; expired rows are
-- ignored by queries (cleanup is an ops task).

CREATE TABLE orders (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_key        TEXT NOT NULL UNIQUE,
    status            TEXT NOT NULL CHECK (status IN ('NEW', 'PAID', 'PACKING', 'SHIPPED', 'COMPLETED', 'CANCELLED')),
    customer_name     TEXT NOT NULL,
    email             TEXT NOT NULL,
    phone             TEXT,
    postcode          TEXT NOT NULL,
    city              TEXT NOT NULL,
    address_line      TEXT NOT NULL,
    note              TEXT,
    ship_method_code  TEXT NOT NULL,
    ship_method_name  TEXT NOT NULL,
    ship_gross_huf    BIGINT NOT NULL,
    items_gross_huf   BIGINT NOT NULL,
    total_gross_huf   BIGINT NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE order_item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    variant_id       BIGINT NOT NULL REFERENCES variant (id),
    product_name     TEXT NOT NULL,
    variant_label    TEXT,
    sku              TEXT,
    unit_gross_huf   BIGINT NOT NULL,
    tax_rate_percent INT NOT NULL,
    quantity         INT NOT NULL CHECK (quantity > 0),
    line_gross_huf   BIGINT NOT NULL
);

CREATE INDEX ix_order_item_order ON order_item (order_id);
-- the availability ledger sums ordered quantity per variant since the last sync
CREATE INDEX ix_order_item_variant ON order_item (variant_id);
CREATE INDEX ix_orders_created_at ON orders (created_at);

CREATE TABLE reservation (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL REFERENCES variant (id),
    cart_token TEXT NOT NULL,
    quantity   INT NOT NULL CHECK (quantity > 0),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (variant_id, cart_token)
);

CREATE INDEX ix_reservation_variant ON reservation (variant_id);

-- switchable 15-minute checkout hold (single-piece / unique items)
ALTER TABLE product ADD COLUMN reserve_on_checkout BOOLEAN NOT NULL DEFAULT FALSE;
