-- Payment attempts (T10, KHPos). One row per gateway init; pay_id is the bank's
-- correlation key. alert marks the "paid but order recording failed" branch for
-- the ops alerting (T23). last_checked_at drives the missing-callback re-check.

CREATE TABLE payment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL REFERENCES orders (id),
    pay_id          TEXT NOT NULL UNIQUE,
    amount_huf      BIGINT NOT NULL,
    state           TEXT NOT NULL CHECK (state IN ('INITIATED', 'CONFIRMED', 'FAILED', 'REVERSED')),
    result_message  TEXT,
    alert           BOOLEAN NOT NULL DEFAULT FALSE,
    last_checked_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_payment_order ON payment (order_id);
CREATE INDEX ix_payment_state ON payment (state);
