-- Customer accounts (T13). Migrated WooCommerce customers keep their phpass hash
-- (stored as {wp}$P$...); on first successful login Spring Security re-encodes it
-- to {bcrypt} (upgrade-on-login). wp_user_id is the migration correlation key.

CREATE TABLE customer (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wp_user_id    BIGINT UNIQUE,
    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    first_name    TEXT,
    last_name     TEXT,
    display_name  TEXT,
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- email is stored lower-cased; this guards case-insensitive uniqueness/lookups
CREATE UNIQUE INDEX ux_customer_email_lower ON customer (lower(email));
